---
name: Eagle to MQTT Bridge
version: dev.1
slug: eagle2mqtt
description: Service listens for messages from the Rainforest Eagle and publishes them to MQTT
url: https://github.com/thevoltagesource/addon-eagle2mqtt
codenotary: jacob@thevoltagesource.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:want
watchdog: http://[HOST]:[PORT:3000]
options:
  mqtt_host: ""
  mqtt_user: ""
  mqtt_pass: ""
  mqtt_topic: eagle
  log_level: info
  summation_watts: false
  ha_discovery: true
schema:
  mqtt_host: str?
  mqtt_user: str?
  mqtt_pass: password?
  mqtt_topic: str
  log_level: list(debug|info)
  summation_watts: bool
  ha_discovery: bool
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Eagle Listener